Assignment-1670-main/Controllers/BookController.cs
using Assignment.Data;
using Assignment.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Assignment.Controllers
{
    
    public class BookController : Controller
    {
        private ApplicationDbContext context;
        public BookController(ApplicationDbContext applicationDbContext)
        {
            context = applicationDbContext;
        }
        [Authorize(Roles = "StoreOwner")]   
        public IActionResult Index()
        {
            var books = context.Book.OrderByDescending(b => b.Id).ToList();
            return View(books);
        }

        [Authorize(Roles = "Customer")]
        public IActionResult Store()
        {
            return View(context.Book.ToList());
        }

        [Authorize(Roles = "StoreOwner")]
        public IActionResult Delete(int id)
        {
            var book = context.Book.Find(id);
            context.Book.Remove(book);
            context.SaveChanges();
            TempData["Message"] = "Delete book successfully !";
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Admin, StoreOwner, Customer")]
        public IActionResult Detail(int id)
        {
            var book = context.Book.Include(b => b.Category) 
                                       .FirstOrDefault(c => c.Id == id);
            return View(book);
        }

        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Category = context.Category.ToList();
            return View();
        }

        [HttpPost]
        public IActionResult Create(Book book)
        {
            ViewBag.Category = context.Category.ToList();
            if (ModelState.IsValid)
            {
                context.Book.Add(book);
                context.SaveChanges();
                TempData["Message"] = "Add new book successfully !";
                return RedirectToAction(nameof(Index));
            }
            return View(book);
        }


        [HttpGet]
        public IActionResult Edit(int id)
        {
            ViewBag.Categories = context.Category.ToList();
            return View(context.Book.Find(id));
        }

        [HttpPost]
        public IActionResult Edit(Book book)
        {
            if (ModelState.IsValid)
            {
                context.Update(book);
                context.SaveChanges();
                TempData["Message"] = "Edit book successfully !";
                return RedirectToAction(nameof(Index));
            }
            return View(book);
        }

        public IActionResult PriceAsc()
        {
            var Books = context.Book.OrderBy(b => b.Price).ToList();
            return View("Store", Books);
        }

        public IActionResult PriceDesc()
        {
            var Books = context.Book.OrderByDescending(b => b.Price).ToList();
            return View("Store", Books);
        }

        [HttpPost]
        public IActionResult Search(string keyword)
        {
            var Books = context.Book.Where(b => b.Title.Contains(keyword)).ToList();
            return View("Store", Books);
        }


        [Route("/checkout")]
        public IActionResult CheckOut()
        {
            return View();
        }
    }
}

Assignment-1670-main/Controllers/CategoryRequestController.cs
using Assignment.Data;
using Assignment.Models;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace Assignment.Controllers
{
    public class CategoryRequestController : Controller
    {
        private ApplicationDbContext context;
        public CategoryRequestController(ApplicationDbContext applicationDbContext)
        {
            context = applicationDbContext;
        }
        public IActionResult Index()
        {
            var request = context.Request.ToList();
            return View(request);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(CategoryRequest request)
        {
            if (ModelState.IsValid)
            {
                context.Add(request);
                context.SaveChanges();
                TempData["Message"] = "Requested a new category to the admin !";
                return RedirectToAction("Create");
            }
            return View(request);
        }

        public IActionResult Approved(int id)
        {
            var request = context.Request.Find(id);
            request.Status = 1;
            context.Request.Update(request);
            context.SaveChanges();
            TempData["Category"] = request.Category;
            return RedirectToAction("Create", "Category");
        }

        public IActionResult Rejected(int id)
        {
            var request = context.Request.Find(id);
            request.Status = -1;
            context.Request.Update(request);
            context.SaveChanges();
            TempData["Message"] = "Request rejected!";
            return RedirectToAction("Index");
        }
    }
}

Assignment-1670-main/Controllers/OrderController.cs
using Assignment.Data;
using Assignment.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace Assignment.Controllers
{
    public class OrderController : Controller
    {
        private ApplicationDbContext context;
        public OrderController(ApplicationDbContext applicationDbContext)
        {
            context = applicationDbContext;
        }

        [Authorize(Roles = "Customer")]
        public IActionResult Create()
        {
            ClaimsPrincipal currentUser = this.User;
            var currentUserID = currentUser.FindFirst(ClaimTypes.NameIdentifier).Value;
            Order o = new Order();
            if (ModelState.IsValid)
            {
                o.UserId = currentUserID;
                o.Status = 0;
                context.Add(o);
                context.SaveChanges();
                TempData["OrderId"] = o.Id;
                return RedirectToAction("Create", "OrderDetail");
            }
            return RedirectToAction("Cart", "Cart");
        }

        public IActionResult Index()
        {
            var user = context.Users.ToList();
            ViewBag.Users = user;
            return View(context.Order.ToList());
        }
        public IActionResult Approved(int id)
        {
            var order = context.Order.Find(id);
            order.Status = 1;
            context.Order.Update(order);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Rejected(int id)
        {
            var order = context.Order.Find(id);
            order.Status = -1;
            context.Order.Update(order);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            var order = context.Order.Include(o => o.OrderDetails).FirstOrDefault(o => o.Id == id);
            foreach (var od in order.OrderDetails)
            {
                var book = context.Book.Find(od.BookId);
                book.Quantity += od.Quantity;
                context.OrderDetail.Remove(od);
            }
            context.Order.Remove(order);
            context.SaveChanges();
            TempData["Message"] = "Delete order successfully !";
            return RedirectToAction("Index");
        }

        public IActionResult Detail(int id)
        {
            var order = context.Order.Include(o => o.OrderDetails)
                                     .ThenInclude(od => od.Book)
                                     .FirstOrDefault(o => o.Id == id);
            return View(order);
        }

        [HttpPost]
        public IActionResult Search(string keyword)
        {
            var customer = context.Users.Where(u => u.Email.Contains(keyword)).ToList();
            var order = context.Order.ToList();
            List<Order> Result = new List<Order>();
            foreach (var o in order)
            {
                foreach (var c in customer)
                {
                    if (o.UserId.Equals(c.Id))
                    {
                        Result.Add(o);
                    }
                }
            }
            var user = context.Users.ToList();
            ViewBag.Users = user;
            return View("Index", Result);
        }
        
        public IActionResult Filter(int status)
        {
            var user = context.Users.ToList();
            ViewBag.Users = user;
            var order = context.Order.Where(o => o.Status.Equals(status)).ToList();
            return View("Index", order);
        }
    }
}

Assignment-1670-main/Controllers/UserController.cs
using Assignment.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;

namespace Assignment.Controllers
{
    public class UserController : Controller
    {
        private ApplicationDbContext context;
        public UserController(ApplicationDbContext applicationDbContext)
        {
            context = applicationDbContext;
        }
        public IActionResult Index()
        {
            var user = context.Users.ToList();
            var userRoles = context.UserRoles.ToList();
            ViewBag.Roles = userRoles;
            return View(user);
        }
        public IActionResult UserOrder()
        {
            var user = context.Users.ToList();
            var order = context.Order.ToList();

            ViewBag.Order = order;
            return View(user);
        }
    }
}

Assignment-1670-main/Views/Shared/CartPartial.cshtml
@using Microsoft.AspNetCore.Http
@using Newtonsoft.Json
@inject IHttpContextAccessor HttpContextAccessor


@{
    var session = HttpContextAccessor.HttpContext.Session;
    string jsoncart = session.GetString(Assignment.Controllers.CartController.CARTKEY);
    if (jsoncart != null)
    {
        var cart = JsonConvert.DeserializeObject<List<CartItem>>(jsoncart);
        <div class="nav-item"><a class="nav-link text-dark" asp-route="cart">Cart(@cart.Count)</a></div>

    }
}

Assignment-1670-main/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FPT Book</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="https://fpt-fti.com/wp-content/uploads/2020/12/FPT_logo.png" height="40" /></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-primary" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            @await Html.PartialAsync("CartPartial")
                        </li>
                        @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-primary" asp-area="" asp-controller="User" asp-action="Index">User</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-primary" asp-area="" asp-controller="Category" asp-action="Index">Categories</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-primary" asp-area="" asp-controller="CategoryRequest" asp-action="Index">Category Request</a>
                            </li>
                        }
                        @if (User.Identity.IsAuthenticated && User.IsInRole("StoreOwner"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-primary" asp-area="" asp-controller="Book" asp-action="">Books</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-primary" asp-area="" asp-controller="CategoryRequest" asp-action="Create">Request Category</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-primary" asp-area="" asp-controller="Order" asp-action="">Order</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-primary" asp-area="" asp-controller="User" asp-action="UserOrder">User Orders</a>
                            </li>
                        }
                        @if (User.Identity.IsAuthenticated && User.IsInRole("Customer"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-primary" asp-area="" asp-controller="Book" asp-action="Store">Store</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-primary" asp-area="" asp-controller="Order" asp-action="">My Order</a>
                            </li>
                        }

                    </ul>

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Assignment
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>